
dataset: 
  data_path: '/usr/local/airflow/data'
  start_date: '2025-01-01'
  end_date: '2025-12-31'
  data_bucket: 'data-sales-forecasting'
  artifact_bucket: 'mlflow-artifacts'
  data_types: 
    - "promotions"
    - "sales"
    - "customer_traffic"
    - "store_events"
    - "inventory"
  required_cols: 
    - 'date'
    - 'store_id'
    - 'product_id'
    - 'quantity_sold'
    - 'revenue'

features: 
  data_features: 
    - "year"
    - "month"
    - "day"
    - "dayofweek"
    - "quarter"
    - "weekofyear"
    - "is_weekend"
    - "is_holiday"
  
  lag_features: 
    - 1
    - 2
    - 3
    - 7
    - 14
    - 21
    - 30
  
  rolling_features: 
    windows: [3, 7, 14, 21, 30]
    funtions: ["mean", "std", "min", "max", "median"]
